In [1]:
import numpy as np

In [2]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [4]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [5]:
A = np.random.randn(10)
A

array([-0.87286224, -0.86752077,  1.11153371, -1.13200205,  0.80320453,
       -1.17411125, -0.42405858, -1.01149182, -0.27724169,  1.04707942])

In [6]:
B = np.random.randn(10)
B

array([ 1.44099624,  0.23585363, -0.8839864 ,  0.04430535, -0.29892074,
        0.12308257,  0.8247374 , -1.38515559,  0.3155693 , -0.2299775 ])

In [7]:
np.add(A, B)

array([ 0.568134  , -0.63166714,  0.22754731, -1.0876967 ,  0.50428379,
       -1.05102868,  0.40067882, -2.39664741,  0.03832761,  0.81710192])

In [8]:
np.maximum(A,B)

array([ 1.44099624,  0.23585363,  1.11153371,  0.04430535,  0.80320453,
        0.12308257,  0.8247374 , -1.01149182,  0.3155693 ,  1.04707942])