In [1]:
import numpy as np

In [5]:
arr = np.arange(9).reshape((3,3))
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
arr.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [7]:
arr.transpose()

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [11]:
arr.transpose(0,1)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [12]:
arr.transpose(1,0)

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [16]:
arr.swapaxes(0,1)

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [17]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [18]:
np.dot(arr.T, arr)

array([[45, 54, 63],
       [54, 66, 78],
       [63, 78, 93]])

In [20]:
arr3d = np.arange(12).reshape((3,2,2))
arr3d

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [21]:
arr3d[0]

array([[0, 1],
       [2, 3]])

In [23]:
arr3d.transpose((0,2,1))

array([[[ 0,  2],
        [ 1,  3]],

       [[ 4,  6],
        [ 5,  7]],

       [[ 8, 10],
        [ 9, 11]]])