In [1]:
import numpy as np

In [2]:
arr = np.arange(5)

In [3]:
np.save('my_array',arr)

In [4]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr1 = np.load('my_array.npy')
arr1

array([0, 1, 2, 3, 4])

In [7]:
arr2 = arr
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.savez('ziparrays.npz',x=arr1,y=arr2)

In [14]:
archive_array = np.load('ziparrays.npz')
archive_array['x']

array([0, 1, 2, 3, 4])

In [15]:
archive_array['y']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr = np.array([[1,2,3],[4,5,6]])
np.savetxt('my_test_text.txt',arr,delimiter=',')

In [17]:
!cat my_test_text.txt

1.000000000000000000e+00,2.000000000000000000e+00,3.000000000000000000e+00
4.000000000000000000e+00,5.000000000000000000e+00,6.000000000000000000e+00


In [18]:
arr = np.loadtxt('my_test_text.txt',delimiter=',')
arr

array([[1., 2., 3.],
       [4., 5., 6.]])