In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [2]:
arr1 = np.arange(9).reshape((3,3))

In [3]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
# 列方向にアレイを連結
np.concatenate([arr1,arr1], axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [5]:
# 行方向にアレイを連結
np.concatenate([arr1,arr1], axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
ser1 = Series([0,1,2],index=['T','U','V'])
ser2 = Series([3,4], index=['X','Y'])
# 行方向の結合
pd.concat([ser1,ser2,ser1])

T    0
U    1
V    2
X    3
Y    4
T    0
U    1
V    2
dtype: int64

In [7]:
# 列方向に連結するとDataFrameになる
pd.concat([ser1,ser2], axis=1)

/Users/tsubasa/.pyenv/versions/anaconda3-5.3.1/lib/python3.7/site-packages/ipykernel_launcher.py:2: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  


0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [8]:
# 階層的なindexを付けて連結
pd.concat([ser1,ser2],keys=['cat1','cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [9]:
pd.concat([ser1,ser2],axis=1,keys=['cat1','cat2'])

/Users/tsubasa/.pyenv/versions/anaconda3-5.3.1/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


cat1  cat2
T   0.0   NaN
U   1.0   NaN
V   2.0   NaN
X   NaN   3.0
Y   NaN   4.0

In [10]:
dframe1 = DataFrame(np.random.randn(4,3), columns=['X','Y','Z'])
dframe2 = DataFrame(np.random.randn(3,3), columns=['Y','Q','X'])

In [11]:
dframe1

X         Y         Z
0 -2.000836 -0.681984 -0.347545
1  0.522506  1.778172  0.715353
2 -0.688073 -0.278177  0.246550
3  0.130595 -0.985007 -2.031660

In [12]:
dframe2

Y         Q         X
0 -0.039416  0.607068  0.563598
1 -1.083911 -0.613950  1.186612
2  0.695320 -0.957642 -1.051123

In [13]:
pd.concat([dframe1,dframe2])

/Users/tsubasa/.pyenv/versions/anaconda3-5.3.1/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


Q         X         Y         Z
0       NaN -2.000836 -0.681984 -0.347545
1       NaN  0.522506  1.778172  0.715353
2       NaN -0.688073 -0.278177  0.246550
3       NaN  0.130595 -0.985007 -2.031660
0  0.607068  0.563598 -0.039416       NaN
1 -0.613950  1.186612 -1.083911       NaN
2 -0.957642 -1.051123  0.695320       NaN

In [14]:
# 元のindexを無視
pd.concat([dframe1,dframe2],ignore_index=True)

/Users/tsubasa/.pyenv/versions/anaconda3-5.3.1/lib/python3.7/site-packages/ipykernel_launcher.py:2: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  


Q         X         Y         Z
0       NaN -2.000836 -0.681984 -0.347545
1       NaN  0.522506  1.778172  0.715353
2       NaN -0.688073 -0.278177  0.246550
3       NaN  0.130595 -0.985007 -2.031660
4  0.607068  0.563598 -0.039416       NaN
5 -0.613950  1.186612 -1.083911       NaN
6 -0.957642 -1.051123  0.695320       NaN

In [15]:
pd.concat([ser1,ser2],axis=1,join_axes=[['U','V','Y']])

0    1
U  1.0  NaN
V  2.0  NaN
Y  NaN  4.0