In [2]:
import numpy as np

my_list1 = [1, 2, 3, 4]
my_array1 = np.array(my_list1)

In [3]:
my_array1

array([1, 2, 3, 4])

In [4]:
my_list2 = [11, 22, 33, 44]

my_lists = [my_list1, my_list2]

my_array2 = np.array(my_lists)

my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [5]:
my_array2.shape

(2, 4)

In [6]:
my_array2.dtype

dtype('int64')

In [7]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [8]:
my_zeros_array = np.zeros(5)

In [9]:
my_zeros_array.dtype

dtype('float64')

In [10]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
np.empty(5)
np.empty((3,4))

array([[4.04738577e-320, 3.16251369e+180, 3.42926747e+169,
        6.18057517e+223],
       [0.00000000e+000, 1.77229088e-310, 3.50977866e+064,
        0.00000000e+000],
       [0.00000000e+000,             nan,             nan,
        3.50977942e+064]])

In [13]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [14]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [15]:
np.arange(5.,50,2)

array([ 5.,  7.,  9., 11., 13., 15., 17., 19., 21., 23., 25., 27., 29.,
       31., 33., 35., 37., 39., 41., 43., 45., 47., 49.])